config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # get 'tasks', to: 'tasks#index'
  # get 'tasks/:id', to: 'tasks#show' as: 'task'
  resources :tasks

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.save
    redirect_to task_path(@task)
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @task.update(task_params)
    redirect_to task_path(@task)
  end

  def destroy
    @task = Task.find(params[:id])
    @task.delete
    redirect_to tasks_path
  end

  private

  def task_params
    params.require(:task).permit(:content, :category, :checked)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<%= form_for @task do |t| %>
  <%= t.text_field :category %>
  <%= t.text_field :content %>
  <%= t.submit %>
<% end %>

app/views/tasks/index.html.erb
<h1>Here is a list of the tasks:  </h1>
<% @tasks.each do |task| %>
  <h2><%= link_to task.category.capitalize,task_path(task) %></h2>
  <p><%= task.content %></p>
<% end %>

app/views/tasks/new.html.erb
<%= form_for @task do |t| %>
  <%= t.text_field :category %>
  <%= t.text_field :content %>
  <%= t.submit %>
<% end %>

app/views/tasks/show.html.erb
<h1><%= @task.category.capitalize %></h1>
<p><%= @task.content %></p>
<p>checked :<%= @task.checked %></p>
<h2><%= link_to "Edit", edit_task_path(@task) %></h2>
<h2><%= link_to "Delete", task_path(@task), method: :delete  %></h2>
<h2><%= link_to "Go back to all tasks", tasks_path%></h2>